In [ ]:
Mean and median
Summary statistics are exactly what they sound like - they summarize many numbers in one statistic. For example, mean, median, minimum, maximum, and standard deviation are summary statistics. Calculating summary statistics allows you to get a better sense of your data, even if there's a lot of it.

sales is available and pandas is loaded as pd.

Instructions
100 XP
Explore your new DataFrame first by printing the first few rows of the sales DataFrame.
Print information about the columns in sales.
Print the mean of the weekly_sales column.
Print the median of the weekly_sales column.

In [1]:
import pandas as pd

In [2]:
sales=pd.read_csv("sales_subset.csv")
sales

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808
...,...,...,...,...,...,...,...,...,...,...
10769,10769,39,A,99,2011-12-09,895.00,False,9.644444,0.834256,7.716
10770,10770,39,A,99,2012-02-03,350.00,False,15.938889,0.887619,7.244
10771,10771,39,A,99,2012-06-08,450.00,False,27.288889,0.911922,6.989
10772,10772,39,A,99,2012-07-13,0.06,False,25.644444,0.860145,6.623
10773,10773,39,A,99,2012-10-05,915.00,False,22.250000,0.955511,6.228

In [3]:
# Print the head of the sales DataFrame
sales.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [4]:
# Print the info about the sales DataFrame
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10774 entries, 0 to 10773
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            10774 non-null  int64
 1   store                 10774 non-null  int64
 2   type                  10774 non-null  object
 3   department            10774 non-null  int64
 4   date                  10774 non-null  object
 5   weekly_sales          10774 non-null  float64
 6   is_holiday            10774 non-null  bool
 7   temperature_c         10774 non-null  float64
 8   fuel_price_usd_per_l  10774 non-null  float64
 9   unemployment          10774 non-null  float64
dtypes: bool(1), float64(4), int64(3), object(2)
memory usage: 768.2+ KB

In [5]:
# Print the mean of weekly_sales
sales["weekly_sales"].mean()

np.float64(23843.95014850566)

In [6]:
# Print the median of weekly_sales
sales["weekly_sales"].median()

12049.064999999999

In [ ]:
Summarizing dates
Summary statistics can also be calculated on date columns that have values with the data type datetime64. Some summary statistics — like mean — don't make a ton of sense on dates, but others are super helpful, for example, minimum and maximum, which allow you to see what time range your data covers.

sales is available and pandas is loaded as pd.

Instructions
100 XP
Print the maximum of the date column.
Print the minimum of the date column.

In [7]:
# Print the maximum of the date column
sales["date"].max()

'2012-10-26'

In [8]:
# Print the minimum of the date column
sales["date"].min()

'2010-02-05'

In [ ]:
Efficient summaries
While pandas and NumPy have tons of functions, sometimes, you may need a different function to summarize your data.

The .agg() method allows you to apply your own custom functions to a DataFrame, as well as apply functions to more than one column of a DataFrame at once, making your aggregations super-efficient. For example,

df['column'].agg(function)
In the custom function for this exercise, "IQR" is short for inter-quartile range, which is the 75th percentile minus the 25th percentile. It's an alternative to standard deviation that is helpful if your data contains outliers.

sales is available and pandas is loaded as pd.

Instructions 3/3
30 XP
Use the custom iqr function defined for you along with .agg() to print the IQR of the temperature_c column of sales.
Update the column selection to use the custom iqr function with .agg() to print the IQR of temperature_c, fuel_price_usd_per_l, and unemployment, in that order.
Update the aggregation functions called by .agg(): include iqr and "median" in that order.

In [9]:
# A custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)
    
# Print IQR of the temperature_c column
sales["temperature_c"].agg(iqr)

np.float64(16.583333333333336)

In [10]:
# A custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

# Update to print IQR of temperature_c, fuel_price_usd_per_l, & unemployment
sales[["temperature_c", "fuel_price_usd_per_l", "unemployment"]].agg(iqr)

temperature_c           16.583333
fuel_price_usd_per_l     0.073176
unemployment             0.565000
dtype: float64

In [11]:
# Create a custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

# Update to print IQR and median of temperature_c, fuel_price_usd_per_l, & unemployment
sales[["temperature_c", "fuel_price_usd_per_l", "unemployment"]].agg([iqr,"median"])

        temperature_c  fuel_price_usd_per_l  unemployment
iqr         16.583333              0.073176         0.565
median      16.966667              0.743381         8.099

In [ ]:
Cumulative statistics
Cumulative statistics can also be helpful in tracking summary statistics over time. In this exercise, you'll calculate the cumulative sum and cumulative max of a department's weekly sales, which will allow you to identify what the total sales were so far as well as what the highest weekly sales were so far.

A DataFrame called sales_1_1 has been created for you, which contains the sales data for department 1 of store 1. pandas is loaded as pd.

Instructions
100 XP
Sort the rows of sales_1_1 by the date column in ascending order.
Get the cumulative sum of weekly_sales and add it as a new column of sales_1_1 called cum_weekly_sales.
Get the cumulative maximum of weekly_sales, and add it as a column called cum_max_sales.
Print the date, weekly_sales, cum_weekly_sales, and cum_max_sales columns.

In [12]:
sales_1_1=sales.copy()

In [13]:
# Sort sales_1_1 by date
sales_1_1 = sales_1_1.sort_values("date", ascending=True)
sales_1_1

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
6437,6437,19,A,13,2010-02-05,38597.52,False,-6.133333,0.780365,8.350
1249,1249,2,A,31,2010-02-05,3840.21,False,4.550000,0.679451,8.324
6449,6449,19,A,14,2010-02-05,17590.59,False,-6.133333,0.780365,8.350
6461,6461,19,A,16,2010-02-05,4929.87,False,-6.133333,0.780365,8.350
...,...,...,...,...,...,...,...,...,...,...
3592,3592,6,A,99,2012-10-05,440.00,False,21.577778,0.955511,5.329
8108,8108,20,A,99,2012-10-05,660.00,False,15.983333,1.052726,7.293
10773,10773,39,A,99,2012-10-05,915.00,False,22.250000,0.955511,6.228
6257,6257,14,A,96,2012-10-12,3.00,False,12.483333,1.056689,8.667
3384,3384,6,A,77,2012-10-26,-21.63,False,22.411111,0.926188,5.329

In [14]:
# Get the cumulative sum of weekly_sales, add as cum_weekly_sales col
sales_1_1["cum_weekly_sales"] = sales_1_1["weekly_sales"].cumsum()

# Get the cumulative max of weekly_sales, add as cum_max_sales col
sales_1_1["cum_max_sales"] = sales_1_1["weekly_sales"].cummax()


# See the columns you calculated
sales_1_1[["date", "weekly_sales", "cum_weekly_sales", "cum_max_sales"]]

             date  weekly_sales  cum_weekly_sales  cum_max_sales
0      2010-02-05      24924.50      2.492450e+04       24924.50
6437   2010-02-05      38597.52      6.352202e+04       38597.52
1249   2010-02-05       3840.21      6.736223e+04       38597.52
6449   2010-02-05      17590.59      8.495282e+04       38597.52
6461   2010-02-05       4929.87      8.988269e+04       38597.52
...           ...           ...               ...            ...
3592   2012-10-05        440.00      2.568932e+08      293966.05
8108   2012-10-05        660.00      2.568938e+08      293966.05
10773  2012-10-05        915.00      2.568947e+08      293966.05
6257   2012-10-12          3.00      2.568947e+08      293966.05
3384   2012-10-26        -21.63      2.568947e+08      293966.05

[10774 rows x 4 columns]

In [ ]:
Dropping duplicates
Removing duplicates is an essential skill to get accurate counts because often, you don't want to count the same thing multiple times. In this exercise, you'll create some new DataFrames using unique values from sales.

sales is available and pandas is imported as pd.

Instructions
100 XP
Remove rows of sales with duplicate pairs of store and type and save as store_types and print the head.
Remove rows of sales with duplicate pairs of store and department and save as store_depts and print the head.
Subset the rows that are holiday weeks using the is_holiday column, and drop the duplicate dates, saving as holiday_dates.
Select the date column of holiday_dates, and print.

In [15]:
# Drop duplicate store/type combinations
store_types = sales.drop_duplicates(subset=["store","type"])
store_types.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
901,901,2,A,1,2010-02-05,35034.06,False,4.550000,0.679451,8.324
1798,1798,4,A,1,2010-02-05,38724.42,False,6.533333,0.686319,8.623
2699,2699,6,A,1,2010-02-05,25619.00,False,4.683333,0.679451,7.259
3593,3593,10,B,1,2010-02-05,40212.84,False,12.411111,0.782478,9.765

In [16]:
# Drop duplicate store/department combinations
store_depts = sales.drop_duplicates(subset=["store","department"])
store_depts.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
12,12,1,A,2,2010-02-05,50605.27,False,5.727778,0.679451,8.106
24,24,1,A,3,2010-02-05,13740.12,False,5.727778,0.679451,8.106
36,36,1,A,4,2010-02-05,39954.04,False,5.727778,0.679451,8.106
48,48,1,A,5,2010-02-05,32229.38,False,5.727778,0.679451,8.106

In [17]:
# Subset the rows where is_holiday is True and drop duplicate dates
holiday_dates = sales[sales["is_holiday"]==True].drop_duplicates(subset=["date"])

# Print date col of holiday_dates
holiday_dates["date"]

498     2010-09-10
691     2011-11-25
2315    2010-02-12
6735    2012-09-07
6810    2010-12-31
6815    2012-02-10
6820    2011-09-09
Name: date, dtype: object

In [ ]:
Counting categorical variables
Counting is a great way to get an overview of your data and to spot curiosities that you might not notice otherwise. In this exercise, you'll count the number of each type of store and the number of each department number using the DataFrames you created in the previous exercise:

# Drop duplicate store/type combinations
store_types = sales.drop_duplicates(subset=["store", "type"])

# Drop duplicate store/department combinations
store_depts = sales.drop_duplicates(subset=["store", "department"])
The store_types and store_depts DataFrames you created in the last exercise are available, and pandas is imported as pd.

Instructions
100 XP
Count the number of stores of each store type in store_types.
Count the proportion of stores of each store type in store_types.
Count the number of stores of each department in store_depts, sorting the counts in descending order.
Count the proportion of stores of each department in store_depts, sorting the proportions in descending order.

In [18]:
# Count the number of stores of each type
store_counts =store_types["type"].value_counts()
store_counts

type
A    11
B     1
Name: count, dtype: int64

In [19]:
# Get the proportion of stores of each type
store_props = store_types["type"].value_counts(normalize=True)
store_props

type
A    0.916667
B    0.083333
Name: proportion, dtype: float64

In [20]:
# Count the number of stores for each department and sort
# store_dept_counts = store_depts["department"].value_counts().sort_values(ascending=False)
dept_counts_sorted = store_depts["department"].value_counts(sort=True)
dept_counts_sorted

department
1     12
2     12
3     12
4     12
5     12
      ..
37    10
48     8
50     6
39     4
43     2
Name: count, Length: 80, dtype: int64

In [21]:
# Get the proportion of stores in each department and sort
# store_dept_props = store_depts["department"].value_counts(normalize=True).sort_values(ascending=False)
dept_props_sorted = store_depts["department"].value_counts(sort=True, normalize=True)
dept_props_sorted

department
1     0.012917
2     0.012917
3     0.012917
4     0.012917
5     0.012917
        ...
37    0.010764
48    0.008611
50    0.006459
39    0.004306
43    0.002153
Name: proportion, Length: 80, dtype: float64

In [ ]:
What percent of sales occurred at each store type?
While .groupby() is useful, you can calculate grouped summary statistics without it.

Walmart distinguishes three types of stores: "supercenters," "discount stores," and "neighborhood markets," encoded in this dataset as type "A," "B," and "C." In this exercise, you'll calculate the total sales made at each store type, without using .groupby(). You can then use these numbers to see what proportion of Walmart's total sales were made at each type.

sales is available and pandas is imported as pd.

Instructions
100 XP
Calculate the total weekly_sales over the whole dataset.
Subset for type "A" stores, and calculate their total weekly sales.
Do the same for type "B" and type "C" stores.
Combine the A/B/C results into a list, and divide by sales_all to get the proportion of sales by type.

In [22]:
# Calc total weekly sales
sales_all = sales["weekly_sales"].sum()
sales_all

np.float64(256894718.89999998)

In [23]:
# Subset for type A stores, calc total weekly sales
sales_A = sales[sales["type"] == "A"]["weekly_sales"].sum()
sales_A

np.float64(233716315.01)

In [24]:
# Subset for type B stores, calc total weekly sales
sales_B = sales[sales["type"] == "B"]["weekly_sales"].sum()
sales_B

np.float64(23178403.89)

In [25]:

# Subset for type C stores, calc total weekly sales
sales_C = sales[sales["type"] == "C"]["weekly_sales"].sum()
sales_C

np.float64(0.0)

In [26]:
# Get proportion for each type
sales_propn_by_type = [sales_A, sales_B, sales_C] / sales_all
print(sales_propn_by_type)

[0.9097747 0.0902253 0.       ]

In [ ]:
Calculations with .groupby()
The .groupby() method makes life much easier. In this exercise, you'll perform the same calculations as last time, except you'll use the .groupby() method. You'll also perform calculations on data grouped by two variables to see if sales differ by store type depending on if it's a holiday week or not.

sales is available and pandas is loaded as pd.

Instructions 1/2
50 XP
1
2
Group sales by "type", take the sum of "weekly_sales", and store as sales_by_type.
Calculate the proportion of sales at each store type by dividing by the sum of sales_by_type. Assign to sales_propn_by_type.

In [27]:
# Group by type; calc total weekly sales
sales_by_type = sales.groupby("type")["weekly_sales"].sum()
sales_by_type

type
A    2.337163e+08
B    2.317840e+07
Name: weekly_sales, dtype: float64

In [28]:
# Get proportion for each type
sales_propn_by_type = sales_by_type/ sum(sales_by_type)
print(sales_propn_by_type)

type
A    0.909775
B    0.090225
Name: weekly_sales, dtype: float64

In [ ]:
Group sales by "type" and "is_holiday", take the sum of weekly_sales, and store as sales_by_type_is_holiday.

In [29]:
# From previous step
sales_by_type = sales.groupby("type")["weekly_sales"].sum()
sales_by_type

type
A    2.337163e+08
B    2.317840e+07
Name: weekly_sales, dtype: float64

In [30]:
# Group by type and is_holiday; calc total weekly sales
sales_by_type_is_holiday =  sales.groupby(["type","is_holiday"])["weekly_sales"].sum()
print(sales_by_type_is_holiday)

type  is_holiday
A     False         2.336927e+08
      True          2.360181e+04
B     False         2.317678e+07
      True          1.621410e+03
Name: weekly_sales, dtype: float64

In [ ]:
Multiple grouped summaries
Earlier in this chapter, you saw that the .agg() method is useful to compute multiple statistics on multiple variables. It also works with grouped data. You can use built-in functions like min, max, mean, and median.

sales is available and pandas is imported as pd.

Instructions
100 XP
Get the min, max, mean, and median of weekly_sales for each store type using .groupby() and .agg(). Store this as sales_stats.
Get the min, max, mean, and median of unemployment and fuel_price_usd_per_l for each store type. Store this as unemp_fuel_stats.

In [31]:
# For each store type, aggregate weekly_sales: get min, max, mean, and median
sales_stats = sales.groupby("type")["weekly_sales"].agg([min,max,"mean","median"])
sales_stats

C:\Users\WIN\AppData\Local\Temp\ipykernel_5820\409679539.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  sales_stats = sales.groupby("type")["weekly_sales"].agg([min,max,"mean","median"])
C:\Users\WIN\AppData\Local\Temp\ipykernel_5820\409679539.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  sales_stats = sales.groupby("type")["weekly_sales"].agg([min,max,"mean","median"])

         min        max          mean    median
type
A    -1098.0  293966.05  23674.667242  11943.92
B     -798.0  232558.51  25696.678370  13336.08

In [32]:
# Print sales_stats
print(sales_stats)

         min        max          mean    median
type
A    -1098.0  293966.05  23674.667242  11943.92
B     -798.0  232558.51  25696.678370  13336.08

In [33]:
# For each store type, aggregate unemployment and fuel_price_usd_per_l: get min, max, mean, and median
unemp_fuel_stats =  sales.groupby("type")[["unemployment","fuel_price_usd_per_l"]].agg([min,max,"mean","median"])
unemp_fuel_stats

C:\Users\WIN\AppData\Local\Temp\ipykernel_5820\1912797488.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  unemp_fuel_stats =  sales.groupby("type")[["unemployment","fuel_price_usd_per_l"]].agg([min,max,"mean","median"])
C:\Users\WIN\AppData\Local\Temp\ipykernel_5820\1912797488.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  unemp_fuel_stats =  sales.groupby("type")[["unemployment","fuel_price_usd_per_l"]].agg([min,max,"mean","median"])
C:\Users\WIN\AppData\Local\Temp\ipykernel_5820\1912797488.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  unemp_fuel_stats =  sales.groupby("type")[["unemployment","fuel_price_usd_per_l"]].agg([min,max,"mean","median"])

     unemployment                         fuel_price_usd_per_l            \
              min    max      mean median                  min       max
type
A           3.879  8.992  7.972611  8.067             0.664129  1.107410
B           7.170  9.765  9.279323  9.199             0.760023  1.107674


          mean    median
type
A     0.744619  0.735455
B     0.805858  0.803348

In [34]:
# Print unemp_fuel_stats
print(unemp_fuel_stats)

     unemployment                         fuel_price_usd_per_l            \
              min    max      mean median                  min       max
type
A           3.879  8.992  7.972611  8.067             0.664129  1.107410
B           7.170  9.765  9.279323  9.199             0.760023  1.107674


          mean    median
type
A     0.744619  0.735455
B     0.805858  0.803348

In [ ]:
Pivoting on one variable
Pivot tables are the standard way of aggregating data in spreadsheets.

In pandas, pivot tables are essentially another way of performing grouped calculations. That is, the .pivot_table() method is an alternative to .groupby().

In this exercise, you'll perform calculations using .pivot_table() to replicate the calculations you performed in the last lesson using .groupby().

sales is available and pandas is imported as pd.

Instructions 3/3
30 XP
Get the mean weekly_sales by type using .pivot_table() and store as mean_sales_by_type.
Get the mean and median of weekly_sales by type using .pivot_table() and store as mean_med_sales_by_type.
Get the mean of weekly_sales by type and is_holiday using .pivot_table() and store as mean_sales_by_type_holiday

In [35]:
# Pivot for mean weekly_sales for each store type
mean_sales_by_type = sales.pivot_table(values="weekly_sales",index="type")

# Print mean_sales_by_type
print(mean_sales_by_type)

      weekly_sales
type
A     23674.667242
B     25696.678370

In [36]:
# Pivot for mean and median weekly_sales for each store type
mean_med_sales_by_type = sales.pivot_table(values="weekly_sales",index="type",aggfunc=(["mean","median"]))

# Print mean_med_sales_by_type
print(mean_med_sales_by_type)

              mean       median
      weekly_sales weekly_sales
type
A     23674.667242     11943.92
B     25696.678370     13336.08

In [37]:
# Pivot for mean weekly_sales by store type and holiday 
mean_sales_by_type_holiday = sales.pivot_table(values="weekly_sales",index="type",columns="is_holiday")

# Print mean_sales_by_type_holiday
print(mean_sales_by_type_holiday)

is_holiday         False      True
type
A           23768.583523  590.04525
B           25751.980533  810.70500

In [ ]:
Fill in missing values and sum values with pivot tables
The .pivot_table() method has several useful arguments, including fill_value and margins.

fill_value replaces missing values with a real value (known as imputation). What to replace missing values with is a topic big enough to have its own course (Dealing with Missing Data in Python), but the simplest thing to do is to substitute a dummy value.
margins is a shortcut for when you pivoted by two variables, but also wanted to pivot by each of those variables separately: it gives the row and column totals of the pivot table contents.
In this exercise, you'll practice using these arguments to up your pivot table skills, which will help you crunch numbers more efficiently!

sales is available and pandas is imported as pd.

Instructions 1/2
50 XP
1
Print the mean weekly_sales by department and type, filling in any missing values with 0.
2
Print the mean weekly_sales by department and type, filling in any missing values with 0 and summing all rows and columns.

In [38]:
# Print mean weekly_sales by department and type; fill missing values with 0
print(sales.pivot_table(values="weekly_sales",index="type",columns="department",fill_value=0))

department            1              2             3             4   \
type
A           30961.725379   67600.158788  17160.002955  44285.399091
B           44050.626667  112958.526667  30580.655000  51219.654167

department            5             6             7             8   \
type
A           34821.011364   7136.292652  38454.336818  48583.475303
B           63236.875000  10717.297500  52909.653333  90733.753333

department            9             10  ...            90            91  \
type                                    ...
A           30120.449924  30930.456364  ...  85776.905909  70423.165227
B           66679.301667  48595.126667  ...  14780.210000  13199.602500

department             92            93            94             95  \
type
A           139722.204773  53413.633939  60081.155303  123933.787121
B            50859.278333   1466.274167    161.445833   77082.102500

department            96            97            98          99
type
A           21367.042857  28471.266970  12875.423182  379.123659
B            9528.538333   5828.873333    217.428333    0.000000

[2 rows x 80 columns]